[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font]
size = 12.0

[window]
opacity = 0.5
dynamic_padding = false

[window.padding]
x = 10
y = 10

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
]
